### ISSUE TITLE
conflit sur le header de recherche

### ISSUE THREAD

**Issue by jlMk** [dpres01/cmbproject#13]
J'avais mit du JS sur bouton de recherche, pour effectuer une recherche.
En examinant le code je vois que tu as retiré ce JS pour lancer la recherche, cela explique pourquoi le bouton ne fonctione plus.

**Comment by dpres01** [comment]
Ah ok j'ai du confondre avec ce que j'avais fait  du coup tu peux repartie su le commit pour le recupéré ou tu veux que je le fasse en suite il faudra le mettre dans le fichier js stp
