### ISSUE TITLE
Style Bouton valider annonces

### ISSUE THREAD

**Issue by dpres01** [dpres01/cmbproject#5]
@jlMk 
QUI : Utilisateur connecter
JE VEUX : travailler le style pour le bouton article vendu dans fichier new annonce;
                Ajouter lien ajax  pour désactiver une annonce

**Comment by jlMk** [comment]
ou se trouve ce bouton?
C'est sur quel page?
Cdt

**Comment by dpres01** [comment]
newAnnonce.html.twig

**Comment by jlMk** [comment]
fixed
