### ISSUE TITLE
Info utilisateur

### ISSUE THREAD

**Issue by dpres01** [dpres01/cmbproject#6]
Dans l'affichage d'une annonce il faut que j obtiennes les infos de l'utlisateur qui a crée l'annonce.
Donne moi un exemple de code dans ZandoController action: afficher annonce

**Comment by dpres01** [comment]
va dans l'action afficherAnnonce ensuite  dans le twig j'ai recuperer le pseudo de l'utilisateur à la ligne 156

**Comment by jlMk** [comment]
fixed
