### ISSUE TITLE
Requete ajax(Annonces et demandes)

### ISSUE THREAD

**Issue by dpres01** [dpres01/cmbproject#8]
@jlMk 
QUI : TOUT UTILISATEUR
JE VEUX : une requete ajax soit lancer au clic sur recherche
POUR : Lancer la recherche

**Comment by dpres01** [comment]
Il faut  créer le service avant, c'est a toi de faire le service

**Comment by dpres01** [comment]
cette recherche te renvoi la liste des annonces donc c'est la methode listeAnnonceAction qu'il faut utiliser.
il pas de service a créer.

**Comment by dpres01** [comment]
Le js va appeler la fonction ajax qui attend comme retour de l'url qu'il va appeler des données en JSON.
La fonction "listerAnnonce" retoune une vue "Zandoo/Annonce/listerAnnonce.html.twig'".

Donc pour moi cette fonction doit changer.

**Comment by jlMk** [comment]
j'attends toujours...

**Comment by dpres01** [comment]
Pour ça jai creer une chercheAnnonceAction dans zandooController pour l'instantant j'ai utiliser une requette ajax dase .html.twig ce que j'attend la reque doit ramener le paramatre 

stp met du js dans le fichier js

**Comment by dpres01** [comment]
cest pareil pour #9

**Comment by jlMk** [comment]
ok comme convenu on passe par un formulaire classique (GET).

**Comment by jlMk** [comment]
ok le formulaire de recherche fonctionne en GET.
le filttre sera fait demain.
